#!/bin/sh

printhelp () {
    printf "Usage: \033[1mcatmd [OPTIONS...] <file>\033[0m\n"
    printf "	-k                      Removes html markup\n"
}

removeHtml=0
while getopts "kh" opt; do
    case "$opt" in
	k)
	    removeHtml=1 ;;
	h)
	    printhelp;
	    exit ;;
    esac
done
shift $((OPTIND-1))


file="$1"
data="$(cat $file)"

#remove html
if [ $removeHtml -eq 1 ]; then
    data="$(echo "$data" | perl -pe 's|<[^>]*?>||g')"
fi

cols=$(tput cols)
i=0
while [ $i -lt $cols ]; do
    hr="$hr-"
    i=$((i + 1))
done

#checklists
data="$(echo "$data" | perl -pe 's|(^\s*)\* (?<!\\)\[ \] (.*)|\1 \\033[31m\[ \]\\033[39m \2|gi')"
data="$(echo "$data" | perl -pe 's|(^\s*)\* (?<!\\)\[x\] (.*)|\1 \\033[32m\[x\]\\033[39m \2|gi')"
#code
data="$(echo "$data" | perl -pe 's|(?<!\\)```(.+)|\\033[32m\1:\\033[9;39m\n------------------------------------\\033[29m\\033[2m|g')"
data="$(echo "$data" | perl -pe 's|(?<!\\)```|\\033[29m\\033[9m------------------------------------\\033[29m|g')"
data="$(echo "$data" | perl -pe 's|(?<!\\)`(.*?)`|\\033[2m\1\\033[29m|g')"
#bullet points
data="$(echo "$data" | perl -pe 's|(^\s*)(?<!\\)(\*\|\+\|-) (.*)|\1* \3|g')"
#bold
data="$(echo "$data" | perl -pe 's|(?<!\\)(\*\|_){2}(.+?)\1{2}|\\033[1m\2\\033[39m|g')"
#italic
data="$(echo "$data" | perl -pe 's|(?<!\\)(\*\|_)([^*\n]+)\1|\\033[3m\2\\033[29m|g')"
#headers
data="$(echo "$data" | perl -pe 's|(?<!\\)^(#+) +(.*)|\\033[2;32m\1\\033[29;39m \\033[4m\\033[1m\2\\033[0m|g')"
#links
data="$(echo "$data" | perl -pe 's|(?<!\\)\[(.+?)\]\((.+?)\)|\\033[1m\1\\033[29m (\\033[34m\2\\033[29m)|g')"
#block quotes
data="$(echo "$data" | perl -pe 's|(?<!\\)(^\s*)>(.*)|\1\|  \2|g')"
#hr
data="$(echo "$data" | perl -pe 's|(?<!\\)^-{3,}$|\\033[9m'$hr'\\033[29m|g')"
#links
data="$(echo "$data" | perl -pe 's|(https?://[^ ]+)|\\033[34m\1\\033[39m|g')"

echo "$data\n"
